---
- hosts: worker-two
  become: yes
  tasks:

    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates 
          - curl 
          - gnupg-agent
          - software-properties-common
        update_cache: yes

    - name: Install docker.io
      apt:
       name: docker.io

    - name: Add user permissions
      shell: |
        usermod -aG docker ${USER}
        chmod 666 /var/run/docker.sock